# Generated by Django 5.1.7 on 2025-03-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sets_reps', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('images', models.JSONField()),
            ],
        ),
    ]
